"""Workflow families supported by the WfCommons-backed builder."""

from __future__ import annotations

from enum import StrEnum


class WorkflowFamily(StrEnum):
    """Workflow families that can be generated by WfCommons."""

    BLAST = "blast"
    BWA = "bwa"
    CYCLES = "cycles"
    EPIGENOMICS = "epigenomics"
    GENOME = "genome"
    MONTAGE = "montage"
    RNASEQ = "rnaseq"
    SEISMOLOGY = "seismology"
    SOYKB = "soykb"
    SRASEARCH = "srasearch"


__all__ = ["WorkflowFamily"]
