name: Build and Deploy to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: make setup-build

      - name: Build the Package
        run: make build

      - name: Verify the distribution
        run: make verify

      - name: Upload to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN_PUBLIC }}
          poetry publish --skip-existing -vv --no-interaction
